### ISSUE TITLE
Crash On Server Boot 1.12 FTB Continuum

### ISSUE THREAD

**Issue by Rajecent** [dries007/MCLink_Mod#10]
Having a crash issue on server boot in MC 1.12

Linked twitch accounts and gathered API data.  
Set config with the twitch settings:

```
 S:Twitch <
		[API Key] Prime 1000 2000 3000
     >
```
Also tried
```

 S:Twitch <
		[API Key]
     >
```
Crash report:

**https://pastebin.com/FvaJTsEK**

Thanks for any assistance in advance.

**Comment by dries007** [comment]
Sorry for the late answer, I missed the email. You need to update your java. You are running `1.8.0_05` which does not have the right certificates to support LetsEncrypt, who is my SSL provider.
