### ISSUE TITLE
Patreon Login Issues 

### ISSUE THREAD

**Issue by ChosenArchitect** [dries007/MCLink_Mod#11]
I am running a server on forge and for some reason, twitch subscribers are having no issues but my Patrons are having a hard time authorizing and when they are authorized they still can't join the server. Has been a problem for about a month now. Any help you be nice!

**Comment by dries007** [comment]
You might have to relink your patreon account. Sometimes their API tokes doesn't renew correctly.
This should be solved permanently when I move over to their new API, but I don't have time to do that until after exams.
To relink without resetting your API key, you can log in on the authe server and use `/link Patreon`.
