### ISSUE TITLE
When Mclink servers go down...

### ISSUE THREAD

**Issue by ChosenArchitect** [dries007/MCLink_Mod#12]
// Quite honestly, I wouldn't worry myself about that.

Time: 7/3/18 4:02 AM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MCLink (mclink)
Caused by: java.net.SocketTimeoutException: connect timed out

Server Crashes.

**Comment by dries007** [comment]
The server outage was due to a faulty router in the datacenter, but this is something that needs to be looked into. Thanks for reporting.
