### ISSUE TITLE
mclink not allowing anyone on

### ISSUE THREAD

**Issue by TGSRagnarok** [dries007/MCLink_Mod#13]
Everyone is getting kicked off atm

**Comment by ChosenArchitect** [comment]
It's not allowing ops or whitelisted people on when mclink servers are down

**Comment by dries007** [comment]
Was there server downtime agian? I need to have words with my datacenter ...
Next update I'm gonna make it so ops and whitelists work even with downtime. Sorry for the inconvenience.

**Comment by TGSRagnarok** [comment]
0.07 02:23:24 [Server] Server thread/INFO [mclink]: Player Player{name='TGSRagnarok', uuid=0d35a30c-83bf-4ad9-a85a-96f067cc01d3} was authorized because they are on the OP list.
10.07 02:23:24 [Server] Server thread/INFO [mclink]: Player Player{name='TGSRagnarok', uuid=0d35a30c-83bf-4ad9-a85a-96f067cc01d3} authorization is being checked anyway...

**Comment by dries007** [comment]
To be clear, is the issues 'solved' now? The servers are reachable now, so it should work fine.

**Comment by TGSRagnarok** [comment]
No it's still not even letting our whitelisted nor ops in let alone the subs

**Comment by dries007** [comment]
There are no errors in my logs, can you send me the token you are using? I'm gonna check if it's still valid. I got a feeling that's the issue.

**Comment by TGSRagnarok** [comment]
udEkbyvC7eGWHCulR93NoM6shA8juAkK

**Comment by dries007** [comment]
That token is not in the database. It seems that my bugfix yesterday caused some tokens to be nuked. I'll investigate why but I can't restore them.
You'll have to get a new one by logging on to the server and using the `api` command.
Sorry for the inconvenience.

ps: I'll try and make sure the messages is clearer with next update.

**Comment by TGSRagnarok** [comment]
OK so our patreon subs and admins are able to log in but the twitch subs are still unable to log in. We've reset the api numerous times

**Comment by dries007** [comment]
OK, I'll have another look when I get home, I'm at work now.

The issues I fixed yesterday meant for some people everyone could log into their servers (it saw everyone as a tier 3 sub), so I hope you understand I can't roll this back.

**Comment by dries007** [comment]
Fixed it (99% sure this time), I made a copy-paste error in my fix yesterday, and in some cases this didn't end up making a difference. It just so happened that all the data I tested with yesterday was this edge case.

Again, Sorry for the inconvenience.
