### ISSUE TITLE
Is MCLink compatible with LuckPerms (Permission Plugin)?

### ISSUE THREAD

**Issue by itsjusttriz** [dries007/MCLink_Mod#14]
I wanna have my server to where a LuckPerms rank is automatically set to a user when they join my server, depending on the Tier of their subscription. Is it possible?

**Comment by dries007** [comment]
I don't use any permissions plugins, so I didn't create any explicit compatibility for any plugin, but I did built in events so it can easily be done I think.
@Brianetta was at some point working on this I think. Any updates on that?

**Comment by itsjusttriz** [comment]
I hope @Brianetta IS working on it, as it would be quite handy and would save the moderators time and effort, joining the server JUST to apply ranks, be it during work hours or basic "stay-away-from-pc" hours

**Comment by Brianetta** [comment]
It's not on my active pile right now (I'm rewriting custom plugins that break on 1.13 for the server I admin) but it's definitely on the radar.

**Comment by Brianetta** [comment]
To confirm, I'm writing *for Luckperms* in the first instance because there appears to be no generic way to apply ranks through Vault.

**Comment by untuned** [comment]
> To confirm, I'm writing _for Luckperms_ in the first instance because there appears to be no generic way to apply ranks through Vault.

Real late reply, but couldn't you specify a command to run instead?

**Comment by dries007** [comment]
Just to close this issue: There is a (paid) beta with LuckPerms integration.

It supports setting groups based on the tier of the support.

Contact me on Discord for more information.
