### ISSUE TITLE
Mixer Subs

### ISSUE THREAD

**Issue by jprocket45** [dries007/MCLink_Mod#15]
not really a issues just figured to ask any chance of adding mixer subs?

**Comment by dries007** [comment]
After I fix the outstanding issues I'll have another look at mixer. Last
time I had issues with their API, so no promises.

Op zo 2 sep. 2018 21:01 schreef jprocket45 <notifications@github.com>:

**Comment by jprocket45** [comment]
ok np!thanks for looking into it, either way thanks for the hard work you put into all your mods!

**Comment by dries007** [comment]
RIP Mixer.
