### ISSUE TITLE
Server Crash - 1.12.2 - Exception in server tick loop

### ISSUE THREAD

**Issue by tjsd** [dries007/MCLink_Mod#16]
Minecraft: 1.12.2
Forge: 2808
MCLink: v3.2.15
Java: Open JRE 8u191
Pack: Project Ozone 3 v3.0.35
Crash: https://termbin.com/b6hm

**Comment by dries007** [comment]
Caused by: java.io.FileNotFoundException: /usr/lib64/libnss3.so


That's the cause. I assume you either removed this file, or installed
system updates and as a result this file got moved.


Op wo 23 jan. 2019 14:50 schreef tjsd <notifications@github.com:

**Comment by tjsd** [comment]
But there is no file called that on my other server where it works, the only difference is the java version.
Server where it is not working:
![image](https://user-images.githubusercontent.com/7138125/51615302-c4f3ac00-1f27-11e9-8aae-7fc688d64c3b.png)
Server where it is working:
![image](https://user-images.githubusercontent.com/7138125/51615361-e81e5b80-1f27-11e9-8c86-3d34d3cf577c.png)

Java versions:
![image](https://user-images.githubusercontent.com/7138125/51616149-c9b95f80-1f29-11e9-8b6e-765363d8df43.png)

**Comment by dries007** [comment]
It's not something I can fix, Java is responsible for the handling of the HTTP_S_ part of the communication.

I assume the underlying library Java uses has changed or been updated, or something went wrong when installing that particular Java version. The only thing I can really say is that's it's not MCLink related. Any HTTPS request would probably result in the same thing.

If you find the solution, feel free to comment, so if it happens again we know how to fix it :)
