### ISSUE TITLE
Link Via Website

### ISSUE THREAD

**Issue by BatteryVoltic** [dries007/MCLink_Mod#17]
Is there a way we get a feature to link our MC account name/uuid via a website with our Twitch accounts. 

Ik that it doesnt take much to go to a server link our accounts and forget about it, however some people have refused to link them because they are forced to long into someone else's server just to gain access to the server they want to get on. 
Also with that being said, if you do make a website linking feature. Could there be a way to to get access to our api or refresh our api.

**Comment by dries007** [comment]
No, it's insecure. Someone could fill in some random details and then boot someone else off the list. Or link accounts they don't have access to. Or link one account, log in, then link their friends, then on and on and on. The current system isn't entirely foolproof, but it's much better than just entering an unchecked, unverified name in a box on a site.

Do these people have any reason other than just being suborn? Maybe I can answer their questions.

You only have to do the login once, it's been made as painless as possible by supporting as many MC versions at once as possible.
