### ISSUE TITLE
Multiple Twitch accounts?

### ISSUE THREAD

**Issue by Kitsumi** [dries007/MCLink_Mod#24]
I have a few friends of mine that I would like to allow their followers to also join. Is this possible?

**Comment by dries007** [comment]
Currently allowing followers is not possible. This might be added in the future.

**Comment by Kitsumi** [comment]
I meant subscribers, I'd like to get subs from a few different channels. Is there a way to do that?

**Comment by dries007** [comment]
Yes, you can add multiple API tokens to the config and as long as you're subscribed to 1 you'll be allowed into the server.

**Comment by Kitsumi** [comment]
Awesome! Thanks so much!
