### ISSUE TITLE
Can MCLink have a config for allowing Twitch Mods, VIPS, and Subs? 

### ISSUE THREAD

**Issue by Swuup** [dries007/MCLink_Mod#25]
Hey! I am trying to allow my twitch subs, mods, and vips to log onto my server and play but I couldn't find a way. Anyone got an example of a config and how I would do it for mods, vips and subs? Thanks, Oppyusa

**Comment by dries007** [comment]
It cannot be done automatically right now. It's on the feature request list.
For subs you can use mclink, and then you must add the mods and vips by hand. You can use the vanilla `/whitelist` command to add people (but you must leave the whitelist disabled!).

If you want "live" support I recommend you join the discord :)
