### ISSUE TITLE
[GameWisp] Linked user can't join my server?

### ISSUE THREAD

**Issue by scalda** [dries007/MCLink_Mod#3]
Hi,

I have finally got the token and such entered into the config file and got the server loading now problem.
I can join the server no problem but i have got one of my pledges testing it and they have successfully linked their accounts as you can see here <img src="https://cdn.discordapp.com/attachments/267184947561889792/392001128314699777/unknown.png" alt="linked">

but they are getting rejected with this message <img src="https://cdn.discordapp.com/attachments/267184947561889792/391999438987460608/unknown.png" alt="Rejected">

and i am getting this in my console [console output ](https://pastebin.com/BbwXzBbm)
Here is my [config](https://pastebin.com/4Ni6BeP0)

Any help would be great thanks

PS. Also how do i whitelist non sub people?

**Comment by dries007** [comment]
You can manually whitelist people by using the vanilla whitelist command (or by making them OP).
Just don't enable the vanilla whitelist. (In theory it should matter, but I've forgotten to deal with that in the past.)

EDIT: I'm analysing the error at the moment, it's possible there is something wrong with the GameWisp API or my integration. While I'm trying to fix it, please don't change your API token, so I can test with it. (I don't have other active GameWisp users I can use to test with.)

**Comment by dries007** [comment]
OK, it should be fixed, I made a typo in the server side code. No change required on your end, although I do recommend you make a new API token. Use `/api reset` in the linking server.

**Comment by scalda** [comment]
thanks for sorting this out, my subs can now successfully join my servers. I also grabbed a new token.

Thanks again
