### ISSUE TITLE
No 1.7.10 version

### ISSUE THREAD

**Issue by Shadou81** [dries007/MCLink_Mod#4]
I'd previously enjoyed using the ForgeSubWhitelist mod to manage my whitelist on my Project Ozone 2 server, but with it not working anymore, I don't have an option for automanaging my whitelist. There aren't any other whitelist mods that look like they're still updating, so with the update to the Twitch API, this is currently the only working whitelist mod that I know of. Will this mod have a 1.7.10 version, or will those server admins that run servers for Regrowth, Project Ozone, or a large percentage of the other huge modpacks out there that still run on 1.7.10 just be SOL?

**Comment by dries007** [comment]
Since I should be able to rip out most of the old mod's code, I think I can get a beta build out quite fast. I'll keep you up to date.
