### ISSUE TITLE
[Mod version] Sponge

### ISSUE THREAD

**Issue by dries007** [dries007/MCLink_Mod#7]
Requested via CurseForge.

Unsure if this is even a good idea, considering the API is so unstable and I don't think anyone uses it without Forge.

**Comment by superon** [comment]
players are reporting issues attempting to log into a twitch sub server with mclink

using MCLink-Forge-1.12.2-0.3.0.14.jar forge-1.12.2-14.23.5.2768-universal.jar and spongeforge-1.12.2-2768-7.1.6-RC3616.jar so wondering if there's an issue here, is sponge not compatible?  i have not seen a sponge-specific file for mclink

**Comment by dries007** [comment]
Can you send me a username/UUID for someone trying to log in and of the server owner (who's API token you're using).
I'll try to get to it ASAP but I'm in the middle the last week before my Thesis hand in, so life is hectic at the moment.

**Comment by superon** [comment]
i believe you was speaking to someone earlier from the server, cheezo...   should i post here? i can't seem to find where to message you direct

**Comment by superon** [comment]
i tested by deopping myself from the server and i am also unable to join.  manually whitelisting allows a connection but i don't want to do this, esp if it's going to conflict

**Comment by dries007** [comment]
Contact info, Discord is preferred nowadays: https://mclink.dries007.net/about
He emailed me, so I have their UUID/username, but I need yours.

Can you log into the verification server and see if the Twitch link is green? I have a suspicion your link may have gotten invalidated for some reason.
