### ISSUE TITLE
dont work for me

### ISSUE THREAD

**Issue by bjelven217** [dries007/MCLink_Mod#9]
i cant do the first step so for them im a patreon for that have MC servers that i have played on a time cant i join now :(

**Comment by dries007** [comment]
Please explain what you are doing exactly and what is happening?
If you are referring to the first step on the help page, please tell me what version of Minecraft you are using, what operating system, if it's a modded client, what mods you are using.
If you fail to connect to the whitelist server, try and connect to `mclink.dries007.net:15556`.
